### ISSUE TITLE
Error adding new csv files

### ISSUE THREAD

**Issue by magejosh** [tritant/sd-webui-creaprompt#1]
I'm not sure if it's my naming convention that is breaking things. I did try to intuit it based on the provided examples. 
Here's the error I'm seeing when I try to use a custom preset that uses a custom csv. 

> *** Error running process: D:\GitHub\stable-diffusion-webui-forge\extensions\sd-webui-creaprompt\scripts\creaprompt.py
    Traceback (most recent call last):
      File "D:\GitHub\stable-diffusion-webui-forge\modules\scripts.py", line 803, in process
        script.process(p, *script_args)
      File "D:\GitHub\stable-diffusion-webui-forge\extensions\sd-webui-creaprompt\scripts\creaprompt.py", line 242, in process
        randprompt= read_random_line_from_csv_files(checkbox_group)
      File "D:\GitHub\stable-diffusion-webui-forge\extensions\sd-webui-creaprompt\scripts\creaprompt.py", line 34, in read_random_line_from_csv_files
        df = pd.read_csv(file_path)
      File "D:\GitHub\stable-diffusion-webui-forge\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
        return _read(filepath_or_buffer, kwds)
      File "D:\GitHub\stable-diffusion-webui-forge\venv\lib\site-packages\pandas\io\parsers\readers.py", line 626, in _read
        return parser.read(nrows)
      File "D:\GitHub\stable-diffusion-webui-forge\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1923, in read
        ) = self._engine.read(  # type: ignore[attr-defined]
      File "D:\GitHub\stable-diffusion-webui-forge\venv\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 234, in read
        chunks = self._reader.read_low_memory(nrows)
      File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
      File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
      File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
      File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
      File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
    pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 42, saw 4

**Comment by magejosh** [comment]
Figured it out, missed a comma on a line in the csv i added. Fixed and works without issue.

**Comment by tritant** [comment]
Hello, I am working on being able to put commas in the csv, this will probably be corrected in the next version
