### ISSUE TITLE
New update has broken the plugin?

### ISSUE THREAD

**Issue by hdglifezach** [tritant/sd-webui-creaprompt#6]
Hello, 

When I whet to use my forgeUI with your plugin today it gives me this error:

*** Error calling: H:\webui\extensions\sd-webui-creaprompt\scripts\creaprompt.py/ui
    Traceback (most recent call last):
      File "H:\webui\modules\scripts.py", line 564, in wrap_call
        return func(*args, **kwargs)
      File "H:\webui\extensions\sd-webui-creaprompt\scripts\creaprompt.py", line 223, in ui
        lines = file.readlines()
      File "codecs.py", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 6100: invalid start byte

any idea if this is a problem on my end or is there something wrong with the new commit?

**Comment by tritant** [comment]
What happened?
